command {
  name = "join",
  level = NORMAL,
  help = "Join a channel",
  aliases = {"j"},
  func = function(evt, chan, user, cmd, channel)
    if type(channel) == "string" then
      local success, reason = apcall(joinN, channel, user)
      if not success then
        sendPM(cfg.server, user, "Could not join the channel: " .. reason)
      else
        local _, pos = isin(users[user].channels, channel)
        users[user].currentTab = pos
        if #users[user].channels > 9 then
          users[user].tabStart = #users[user].channels - 9
        end
      end
    else
      help(user, "join")
    end
  end
}

command {
  name = "part",
  level = NORMAL,
  help = "Leave a channel",
  func = function(evt, chan, user, cmd, channel, msg)
    msg = msg or ""
    if isin({"string", "nil"}, type(channel)) then
      if tonumber(channel) then
        local tn = tonumber(channel)
        channel = users[user].channels[tn]
        if not channel then
          sendPM(user, cfg.server, "Wrong tab")
        end
      else
        channel = chan
      end
      if channel == cfg.main_channel then
        sendPM(cfg.server, user, "You can't leave #main!")
        return -1
      end
      local _, was = isin(users[user].channels, channel)
      local success, reason = apcall(partN, channel, user, msg)
      if not success then
        sendPM(cfg.server, user, "Could not leave the channel: " .. reason)
      else
        if users[user].currentTab == was then
          users[user].currentTab = users[user].currentTab - 1
          users[user].startTab = users[user].currentTab - 9
          if users[user].startTab < 1 then
            users[user].startTab = 1
          end
        end
      end
    else
      help(user, "part")
    end
  end
}

command {
  name = "tab",
  level = NORMAL,
  help = "Open tab",
  aliases = {"t"},
  func = function(evt, chan, user, cmd, tab)
    if tonumber(tab) then
      tab = tonumber(tab)
      if tab > 0 and tab <= #users[user].channels then
        users[user].currentTab = tab
      else
        sendPM(cfg.server, user, "Wrong tab num")
        return 1
      end
    elseif type(tab) == "string" then
      local exists, pos = isin(users[user].channels, tab)
      if exists then
        users[user].currentTab = pos
      else
        sendPM(cfg.server, user, "No such channel")
        return 1
      end
    else
      help(user, "tab")
    end
    users[user].startTab = users[user].currentTab - 9
    if users[user].startTab < 1 then
      users[user].startTab = 1
    end
  end
}

command {
  name = "topic",
  level = NORMAL,
  help = "Set channel's topic",
  func = function(evt, chan, user, cmd, channel, ...)
    local topic = table.concat({...}, " ")
    channel = channel or ""
    if channel:sub(1, 1) ~= "#" then
      topic = channel .. (topic and topic ~= "" and " " .. topic or "")
      channel = chan
    end
    if not channels[channel] or not channels[channel].users[user] then
      sendPM(cfg.server, user, "You are not in channel")
      return -1
    end
    if not isin(channels[channel].modes, "t") or checkLevel(chan, user, {HALFOP, OP}, true) then
      channels[channel].topic = topic
      sendNotifyChan(channel, "topic", {user, topic})
    else
      sendPM(cfg.server, user, "You are not allowed to do this")
    end
  end
}

command {
  name = "kick",
  level = HALFOP,
  help = "Kick a user from channel",
  func = function(evt, chan, user, cmd, channel, arg, msg)
    if not channel then
      help(user, "kick")
      return -1
    end
    if channel:sub(1, 1) ~= "#" then
      msg = arg
      arg = channel
      channel = chan
    end
    msg = msg or user
    if not arg then
      help(user, "kick")
      return -1
    end
    if not users[arg] then
      sendPM(cfg.server, user, "No such user")
      return 1
    end
    if not channels[channel] or not channels[channel].users[user] then
      sendPM(cfg.server, user, "You are not in the channel")
      return 1
    end
    if channel == cfg.main_channel then
      sendPM(cfg.server, user, "You can't kick the user from #main")
      return 1
    end
    if isin(cfg.admins, arg) or cfg.server == arg then
      sendPM(cfg.server, user, "You are not allowed to kick the admin")
    end
    local success, reason = apcall(partN, channel, arg, "Kicked by " .. user .. ": " .. msg)
    if not success then
      sendPM(cfg.server, user, "Could not kick a user: " .. reason)
    end
  end
}

-- vim: autoindent expandtab tabstop=2 shiftwidth=2 syntax=lua :
