command {
  name = "msg",
  level = NORMAL,
  help = "Send private message to user",
  aliases = {"m", "pm"},
  func = function(evt, chan, user, cmd, addressee, ...)
    local msg = table.concat({...}, " ")
    if not addressee or msg == "" then
      help(user, "msg")
      return -1
    end
    local success, reason = apcall(sendPM, addressee, user, msg)
    if not success then
      sendPM(user, cfg.server, "Could not send a PM: " .. reason)
    end
  end
}

-- vim: expandtab tabstop=2 shiftwidth=2 syntax=lua :
